### ISSUE TITLE
[New-Service] Gopher Service

### ISSUE THREAD

**Issue by coyote240** [DEFCONMeshNet/DEFCONMeshNet#2]
**Owner**
signal9

**On Mesh IP Address or Defcon Domain Name**
gopher://[201:dc0a:31ba:dac7:8461:fc7:f41e:586]

**Description of Service**
Simple gopher site. Minimal content for now, will expand and add interactivity in the coming weeks.

**Comment by coyote240** [comment]
It occurs to me, after a DNS record is added, this service will also be available at:

gopher://vexing.defcon

**Comment by cyberbalsa** [comment]
Can't seem to to ping your on-mesh IP address. Please make sure that the internal Ygg firewall is not enabled for the machine hosting the services. Also I attempted to connect to the service using Lynx without success

**Comment by coyote240** [comment]
Thanks. Do you recommend disabling the SessionFirewall entirely, or simply setting AllowFromDirect and AllowFromRemote to true?

**Comment by cyberbalsa** [comment]
for public services, I would just disable it outright and use IPTables/UFW for firewalling if required.

**Comment by cyberbalsa** [comment]
Confirmed online 
![image](https://user-images.githubusercontent.com/804052/83992227-90667180-a91d-11ea-9761-e5943e98fdf9.png)

**Comment by coyote240** [comment]
Thanks!

**Comment by coyote240** [comment]
I was wrong about my target domain earlier, if it matters. Site is available at gopher://vexingco.user.defcon.

thanks again
