### ISSUE TITLE
Is the matrix server down?

### ISSUE THREAD

**Issue by bbigras** [DEFCONMeshNet/DEFCONMeshNet#3]
It doesn't seem available. Also note that the URL in this repo's readme doesn't match the one on https://defconmesh.net/.

Also do you people know about the matrix yggdrasil demo? https://matrix.org/blog/category/this-week-in-matrix#riot-ios-p2p-demo

The demo is also runnable on desktop.

Also on Android but dendrite needs to be compiled with termux one something like that. and patched to fake the client-server api version. and riotx can't create the user but log-in works.

#p2p:matrix.org

**Comment by McL0v1n** [comment]
Fixed, the issue was it swapped from riot to element

**Comment by bbigras** [comment]
Is the matrix server reachable on the mesh network? The readme has an ipv6 address but I can't connect.

https://github.com/DEFCONMeshNet/DEFCONMeshNet/blame/master/README.md#L47

**Comment by McL0v1n** [comment]
@bbigras Matrix requires the use of DNS,  you have to navigate via it's domain name due to a series of reverse proxies that are set up to facilitate it's use.

**Comment by bbigras** [comment]
@McL0v1n gotcha. thanks
