### ISSUE TITLE
[New-DNS] gulo.defcon

### ISSUE THREAD

**Issue by GuloGuloDesu** [DEFCONMeshNet/DEFCONMeshNet#4]
**Domain Name**
gulo.defcon

**DNS Records**
@ NS ns1.gulo.defcon
ns1 AAAA 0200:22eb:af90:9426:6080:eb68:8dec:a44b

**Owners**
Gulo
GuloGuloDesu

**Readme**

You can have as many DNS records as you like, we do not require a root NS record to be selected, a root AAAA record on @ is prefectly fine, wildcard CNAMEs are allowed for subdomains as well.

**Comment by McL0v1n** [comment]
Your name delegation has been added. Please allow time for the zone to propagate to all DNS Servers.
