### ISSUE TITLE
Update the Matrix link

### ISSUE THREAD

**Issue by b0nefolder** [DEFCONMeshNet/DEFCONMeshNet#5]
**Describe the bug**
The DefconMeshnet Matrix link points to https://riot.defconmesh.net which does not resolve. The link should be https://element.defconmesh.net

**To Reproduce**
Click the DefconMeshnet Matrix link on https://defconmesh.net/

**Expected behavior**
The login page for the defcon matrix is presented.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Any
 - Browser: Any
 - Version: Any

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser
 - Version 

**Additional context**

**Comment by McL0v1n** [comment]
Completed.
